name: Build and Upload AirDao Nop Binary

on:
  push:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Get version from Cargo.toml
      id: get_version
      run: |
        version=$(curl -s https://raw.githubusercontent.com/ambrosus/airdao-nop-rs/main/Cargo.toml | grep '^version' | sed -E 's/version = "(.*)"/\1/')
        echo "VERSION=$version" >> $GITHUB_ENV

    - name: Create Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release create "v${VERSION}" --title "Release v${VERSION}" --notes "Automated release based on merged PR."

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.81
        override: true
        components: rustfmt, clippy
        target: x86_64-unknown-linux-gnu

    - name: Cache cargo registry and git dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.toml') }}
        restore-keys: |
          ${{ runner.os }}-cargo-

    - name: Build binary
      run: |
        git submodule update --init --recursive
        RUSTFLAGS='-C link-arg=-s' cargo build --release --target x86_64-unknown-linux-gnu

    - name: Archive 
      run: zip -j airdao-nop-rs-x86-64.zip target/x86_64-unknown-linux-gnu/release/airdao-nop-rs

    - name: Upload to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.get_version.outputs.upload_url }}
        asset_path: ./airdao-nop-rs-x86-64.zip
        asset_name: airdao-nop-rs-x86-64.zip
        asset_content_type: application/zip
      with:
        upload_url: ${{ github.event.repository.releases[0].upload_url }}
        asset_path: ./airdao-nop-rs-x86-64.zip
        asset_name: airdao-nop-rs-x86-64.zip
        asset_content_type: application/zip
